general.import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]
# font_family = "Mononoki Nerd Font"
# font_size = "20"


[font]
size = 14
# normal = { family = "%font_family", style = "Regular" }
# bold = { family = "%font_family", style = "Bold" }
# italic = { family = "%font_family", style = "Italic" }
# bold_italic = { family = "%font_family", style = "Bold Italic" }
# size = 20

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[window]
dimensions = { columns = 120, lines = 36 }
padding = { x = 0, y = 0 }
decorations = "Full"
dynamic_padding = true
blur = true
startup_mode = "Windowed" # "Maximized" "Fullscreen" "SimpleFullscreen"
opacity = 1

[cursor]
style = { shape = "Underline", blinking = "Always" } #"Block" "Underline", "Beam"
vi_mode_style = "None"
blink_interval = 500
# blink_timeout = 0
# thickness = 0.1

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "L", mods = "Control|Shift", chars = "la" },
]
